### PR TITLE
Calculate Power Functions

### PR DESCRIPTION
**Pull request by jansoromeo**
Hi

this pull request contains two functions for calculating power.
[powerFromTimeDomain] = getPowerFromTimeDomain(combinedDataTable,settings); % outputs default 8 power bands using default power band settings and time domain channels
[newPowerFromTimeDomain, newSettings] = calculateEquivalentDevicePower(combinedDataTable, settings, channel, freqBand)  % for 1 time domain channel outputs a new power series given a new frequency band limit

The only addition to preexisting code is 
- createDeviceSettingsTable (lines 37-39)
 % Get actual amplifier gains
ampGains = getActualAmplifierGains(folderPath);
metaData.ampGains = ampGains;

### Wrapper code to add to the existing DEMO_LoadRCS.m wrapper
...
% Create equivalent device power -- use timeDomain data as time base
settings = {fftSettings,powerSettings,metaData};
[powerFromTimeDomain] = getPowerFromTimeDomain(combinedDataTable,settings); % outputs default 8 power bands using default power band settings
[newPowerFromTimeDomain, newSettings] = calculateEquivalentDevicePower(combinedDataTable,settings,1,[10 15]); % for 1 time domain channel outputs a new power series given a new band limit

Best,
Juan

### CODE REVIEW

**Comment by kristinksellers** [comment]
In `getPowerFromTimeDomain`, in top description update `DEMO_Process` to `ProcessRCS.m`.

**Comment by kristinksellers** [comment]
In `getPowerFromTimeDomain`, can `fftSettings`, `powerSettings`, `metaData` be inputs rather than putting into `settings`? These will be loaded the workspace, so user doesn't need to rename anything

**Comment by kristinksellers** [comment]
Error: 
image

image

**Comment by kristinksellers** [comment]
getPowerFromTimeDomain.m, Line 54 -- 'equivalent to Hann 100%'. Should this match fftConfig.windowLoad? (25%, 50%, or 100% hann)

**Comment by kristinksellers** [comment]
Input 'c' isn't used in `readFFTsettings`

**Comment by kristinksellers** [comment]
Subfunction `createAmplifierGainsTable` in `getPowerFromTimeDomain` no longer used, should be removed

**Comment by kristinksellers** [comment]
Initialization error in `calculateEquivalentDevicePower`

image

**Comment by jansoromeo** [comment]
hi
updated pull request branch with a DEMO_CalculatePowerRCS.m and the adjustments suggested by Kristin from last request.
Juan

**Comment by jansoromeo** [comment]
BTW, I also pulled the Master into the branch, so now the merging into the Master is automatic without need to merge on your side. There shouldn't be conflicts. Just need to add a few new lines to the documentation, once you give it ago on your side.

**Comment by kristinksellers** [comment]
@jansoromeo Looking good! 

Suggested updates for `getPowerFromTimeDomain.m`: 
- Make more clear in top comments that `calculationType` inputs can be '1' or '2'. If using `calculationType` = 1, likely don't want to create `partialPowerTables` -- requires 2x the memory and redundant information. Also consider renaming `partialPowerTables` to sometime like `powerTablesBySetting` (otherwise may be confusing when you think of partial FFT --> partial power??)

- When selecting calculationType '2', create full rows of data and then write to table to avoid getting warning
image

- Line 75: Update comment to say 256 ch

**Comment by kristinksellers** [comment]
It looks like `calculateEquivalentDevicePower` requires that power data were collected in the recording (because dependent on powerSettings.powerBands.fftBins in line 42). Ideally, could use this function to calculate power even if only time domain was recorded

**Comment by jansoromeo** [comment]
> It looks like `calculateEquivalentDevicePower` requires that power data were collected in the recording (because dependent on powerSettings.powerBands.fftBins in line 42). Ideally, could use this function to calculate power even if only time domain was recorded

I know - it would be great. For now, it's constrained to using the set of bins given by the datasets predefined FFT settings.

**Comment by jansoromeo** [comment]
> Getting this error for both functions on a test file -- will send recording via Box:
> image

I added some code to handle that the output of hannWindow matches the length of L...

**Pull request merged**
